"""Initial revision

Revision ID: fcc8536ed9fa
Revises: 3f7a13f48b56
Create Date: 2025-07-16 16:06:50.334849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc8536ed9fa'
down_revision: Union[str, Sequence[str], None] = '3f7a13f48b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_rooms', sa.Column('capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_rooms', 'capacity')
    # ### end Alembic commands ###
